server:
   port: 8888

spring:
  application:
    name: hr-config-server
  cloud:
    config:
      server:
        git:
          default-label: ${GITHUB_BRANCH}
          uri: ${GITHUB_URI}
          ignore-local-ssh-settings: true
          host-key-algorithm: ${HOST_KEY_ALGORITHM}
          host-key: ${HOST_KEY}
          passphrase: ${PASSPHRASE}
          private-key: |
            -----BEGIN RSA PRIVATE KEY-----
            Proc-Type: 4,ENCRYPTED
            DEK-Info: AES-128-CBC,927CDC6E923705AE72BF68C372DC14BD
            
            muWVVAdUvEaG6XDNxGmg6v1Qb47cjARM4+ArIyn50njXcArEcl19iYgpENKdrZ2h
            QwY53ZpSdyigDoZqSwv4hBy/5Oe9UxPaRMYOEXgXWSu4947izJCvgp5Xt9yich6Q
            /f+dseQAji0QeR8L5Q0uGVW3AHDKUAvd+7tnd+lxT8QlXFFLuCSoq4KdvJvasptQ
            KdZCQPpJgXxwRuD2MRqfG7bBaNpk9G0qPpURHuFbMY6M6PWzP6dW30jSMPu17Sph
            bU+VBVvXfgicAZ5bYXAul4CgfvIR8x14juJp56bwYyp3qrLBqSRHYzopgnspZU1j
            s5BP27HCNFNWQWpz/elbbh7BRI8S0++JvBI59cXDAZRpjFjlOvyRyo9cSKKWUidR
            i9CUTVM9U+eoU1vDFo2n2axDnNw/NxKqJoLsmKl3w07F+fOO55F4ZpmUPEozT4uk
            lCs6AzFLy/sEs7jbPHJUipQJVQK7LMBtPPs0qxeHZh1XLt6YtOISQEipHc2wm6zV
            xpklpRIpPMF8FELfSpwPucNnCBBHlb1zsZaaeDbJ22vEt94KdCPnONOmhKzQySsQ
            iPkrVEDQNb8HuO9aWSjfD6R5RHUjflPVgVmEXlcNCsVFuOEzZ72PzIFYmFSBoGon
            2QIhaLsNj1OvMdZBon0dUmHh7s8K9HRbtXcau/vLG+u/xuj0SDUyZN7PlIO5Jh8O
            tAHEOknP9FB49WbevPbUqZ7DOAns89P5AWqC1ncIIDq1jVc9sPJzEAMCAtaiA4wO
            4f4R4UX5wLOKL7Ylfk6M4EmQdGLWBMerYL+led0ZFy9eYyAOh6Jc2bZokE/01CdW
            iOwS60zlamZYJmqkE/WrVwpLK2LLSfx8zM1cuRbc2ffwzgHg1mYTERkC5QBb4CEJ
            gTqrDQ7K6841zowpgNNEpCQCD9E/JrNq1iC9uhc8YGZoPWH2qpF07Fq/CM/W8/0h
            vr3cYfC5jmE2iuQ+ZfLsF8b5re02P3fYuYYDbeErYy0N2DZtJU0xf85jCqnKt9o/
            b19/uybe7SC6oFWFHIUtF2E1E1Jshi5wKxy9dBHZZRLmH4U7QbbKze2mD+ar9mDj
            7AOSpQr2O6CsanittKIImSu1XveIFDsLfVXECOW3TIrQLTxhFX0RW/CKO05sMhnZ
            D9vEQzVMydqzMYa2Tx9P5vGqYEsx+UCU4NqPBA5+HDFsB7y+gGRgxg3jxI7aWwqz
            57O+DaY1QueE4yz/gbSHFD7Q410SOl7y/ruS1cUGmv5JS17fDF7dPqVWWEbBj+H/
            BF7zZDTZCbU2RFaarQNOmfpevVpzEBuwfjhlawCcxpqS1AnwYB2bKQMde0iV6L4i
            aTPvD1+TipZGQWxDjlpAKXEDrHuRJrxaGDmQu/Gi51ummBVPbg0iJwfAvvWUpGr2
            HlXcUWLqZ/nKHYLes+dO5mp6C3Q3USHs3no/kwEVbGVp4CCLsgB9rM/lko+y76q4
            AC3pqGN65j8P/byf9yIIx7OWLhDKewWw3mfA8D0wuaIJHYICyXJPzK5cmjSRdZHO
            u66c2cAK+1RAS0lYr/hYdUFluFQ0BR52IGaC/2v0q/mBKZXnBpwcTn+scTfEqtDp
            -----END RSA PRIVATE KEY-----