server:
   port: 8888

spring:
  application:
    name: hr-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gustosilva/ms-course-config
          username: ${GITHUB_USER}
          password: ${GITHUB_PASS}
          default-label: main