server:
  port: 8765

spring:
  application:
    name: hr-api-gateway-zuil

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
zuul:
  routes:
    worker:
      service-id: hr-worker
      path: /hr-worker/**
    user:
      service-id: hr-user
      path: /hr-user/**
    payroll:
      service-id: hr-payroll 
      path: /hr-payroll/**
    oauth:
      service-id: hr-oauth 
      path: /hr-oauth/**
      
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 20000