server:
  port: 8765

spring:
  application:
    name: hr-api-gateway-zuul

zuul:
  routes:
    oauth:
      path: /hr-oauth/**
      sensitive-headers: Cookie,Set-Cookie
      service-id: hr-oauth
    payroll:
      path: /hr-payroll/**
      service-id: hr-payroll
    user:
      path: /hr-user/**
      service-id: hr-user
    worker:
      path: /hr-worker/**
      service-id: hr-worker

eureka:
  client:
    service-url:
      defaultZone: http://hr-eureka-server:8761/eureka

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 20000



